name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check npm version
        run: |
          npm --version

      - name: Install Retype
        run: |
          npm install -g retype
          
      - name: Verify Retype installation
        run: |
          which retype || echo "Retype not found"
          retype --version || echo "Retype version command failed"

      - name: Verify .retype directory
        run: |
          ls -l .retype || echo ".retype directory does not exist"

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check npm version
        run: |
          npm --version

      - name: Install Retype
        run: |
          npm install -g retype
          
      - name: Verify Retype installation
        run: |
          which retype || echo "Retype not found"
          retype --version || echo "Retype version command failed"

      - name: Verify .retype directory before deploy
        run: |
          ls -l .retype || echo ".retype directory does not exist"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .retype
